@startuml

start

    repeat

        :Search element 
        :Found element between start and finish index. Middle element;

        if ("MiddleItem == sought?") then (yes)
            :Search finished;
            :Return middle element index;
            stop
        elseif ("StartItem == sought?") then (yes)
            :Search finished;
            :Return start element index;
            stop
        elseif ("FinishItem == sought?") then (yes)
            :Search finished;
            :Return finish element index;
            stop
        elseif ("MiddleItem > sought?") then (yes)
            :FinishIndex = MiddleIndex - 1;
        elseif ("MiddleItem < sought?") then (yes)
            :StartIndex = MiddleIndex + 1;
        endif

    repeat while (startIndex < finishIndex) is (no)

    :Search finished;
    :Return no item found result;

stop

@enduml