@startuml

start

partition "quickSort(minArrayIndex, maxArrayIndex)" {
    :set Pivot as last element;
    :set smallestElementIndex = minArrayIndex - 1;
    :set currentElementIndex = minArrayIndex;

    repeat
        if (item at index currentElementIndex less or equal to Pivot) then (yes)
            :smallestElementIndex++;
            :swapElementsWithIndexes(currentElementIndex, smallestElementIndex);
        endif
        :currentElementIndex++;
    repeat while (currentElementIndex == pivot index) is (no)

    :partitionElementIndex = smallestElementIndex+1;
    :swapElementsInArray(partitionElementIndex, pivotIndex);
}

:quickSort(minArrayIndex, partitionElementIndex-1);
:quickSort(partitionElementIndex+1, maxArrayIndex);

stop

@enduml