@startuml

start

:Set path from the start point to start point is 0;
:Set start point is base vertex;

repeat

    :Calculate path from base to neibours as
    path to base vertex + edge weight;
    if (Path to neibour shortest than already calculated) then (yes)
        :Overwrite shortest path;
    endif

    repeat
        if (Shortest path) then (yes)
            :Set vertex with shortest path as resolved;
            :Set vertex with shortest path as new base vertex;
        endif
    repeat while (End of vertex list) is (no)

repeat while (All vertexes resolved) is (no)

stop

@enduml